Update release-50_publish-docker.yml
debug1

diff --git a/.github/workflows/release-50_publish-docker.yml b/.github/workflows/release-50_publish-docker.yml
--- a/.github/workflows/release-50_publish-docker.yml
+++ b/.github/workflows/release-50_publish-docker.yml
@@ -95,21 +95,21 @@ jobs:
         #   chmod a+x $BINARY
         #   ls -al
 
-      - name: Fetch rc artifacts or release artifacts based on release id
-        #this step runs only if the workflow is triggered manually
-        if: ${{ env.EVENT_NAME  == 'workflow_dispatch' }}
-        run: |
-          . ./.github/scripts/common/lib.sh
-
-          fetch_release_artifacts
-
-      - name: Cache the artifacts
-        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
-        with:
-          key: artifacts-${{ env.BINARY }}-${{ github.sha }}
-          path: |
-            ./release-artifacts/${{ env.BINARY }}/**/*
-
+#      - name: Fetch rc artifacts or release artifacts based on release id
+#        #this step runs only if the workflow is triggered manually
+#        if: ${{ env.EVENT_NAME  == 'workflow_dispatch' }}
+#        run: |
+#          . ./.github/scripts/common/lib.sh
+#
+#          fetch_release_artifacts
+#
+#      - name: Cache the artifacts
+#        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
+#        with:
+#          key: artifacts-${{ env.BINARY }}-${{ github.sha }}
+#          path: |
+#            ./release-artifacts/${{ env.BINARY }}/**/*
+#
   build-container: # this job will be triggered for the polkadot-parachain rc and release or polkadot rc image build
     if: ${{ inputs.binary == 'polkadot-parachain' || inputs.image_type == 'rc' }}
     runs-on: ubuntu-latest
@@ -120,28 +120,28 @@ jobs:
       - name: Checkout sources
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
-      - name: Get artifacts from cache
-        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
-        with:
-          key: artifacts-${{ env.BINARY }}-${{ github.sha }}
-          fail-on-cache-miss: true
-          path: |
-            ./release-artifacts/${{ env.BINARY }}/**/*
+#      - name: Get artifacts from cache
+#        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
+#        with:
+#          key: artifacts-${{ env.BINARY }}-${{ github.sha }}
+#          fail-on-cache-miss: true
+#          path: |
+#            ./release-artifacts/${{ env.BINARY }}/**/*
 
-      - name: Check sha256 ${{ env.BINARY }}
-        working-directory: ./release-artifacts/${{ env.BINARY }}
-        run: |
-          . ../../.github/scripts/common/lib.sh
+#      - name: Check sha256 ${{ env.BINARY }}
+#        working-directory: ./release-artifacts/${{ env.BINARY }}
+#        run: |
+#          . ../../.github/scripts/common/lib.sh
 
-          echo "Checking binary $BINARY"
-          check_sha256 $BINARY && echo "OK" || echo "ERR"
+#          echo "Checking binary $BINARY"
+#          check_sha256 $BINARY && echo "OK" || echo "ERR"
 
-      - name: Check GPG ${{ env.BINARY }}
-        working-directory: ./release-artifacts/${{ env.BINARY }}
-        run: |
-          . ../../.github/scripts/common/lib.sh
-          import_gpg_keys
-          check_gpg $BINARY
+#      - name: Check GPG ${{ env.BINARY }}
+#        working-directory: ./release-artifacts/${{ env.BINARY }}
+#        run: |
+#          . ../../.github/scripts/common/lib.sh
+#          import_gpg_keys
+#          check_gpg $BINARY
 
       - name: Fetch rc commit and tag
         if: ${{ env.IMAGE_TYPE == 'rc' }}
